---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write

  integration:
    needs: 'lint-unit'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'almalinux-8'
          - 'almalinux-9'
          - 'amazonlinux-2023'
          - 'centos-stream-9'
          - 'centos-stream-10'
          - 'oraclelinux-8'
          - 'oraclelinux-9'
          - 'rockylinux-8'
          - 'rockylinux-9'
        suite:
          - 'default'
          - 'all'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Chef
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Dokken
        run: kitchen test ${{ matrix.suite }}-${{ matrix.os }} --destroy=always
        env:
          CHEF_LICENSE: accept
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
